# Generated by Django 3.2.5 on 2023-05-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overallperformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.URLField(max_length=255)),
                ('mobile', models.TextField(max_length=255)),
                ('desktop', models.TextField(max_length=255)),
            ],
        ),
    ]
