# Generated by Django 3.2.5 on 2023-05-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sitemapapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xmls', models.URLField(max_length=255)),
                ('borkenlinks', models.TextField(blank=True)),
                ('workinglinks', models.TextField(blank=True)),
            ],
        ),
    ]
