# Generated by Django 3.2.5 on 2023-05-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitemapapi',
            old_name='borkenlinks',
            new_name='brokenlinks',
        ),
    ]
